### ISSUE TITLE
Safer way of mixing in functions?

### ISSUE THREAD

**Issue by joshuacc** [documentcloud/underscore-contrib#108]
Currently, the way that contrib is built, all of a sub-library's functions are automatically mixed in to Underscore. This works if you are using only Underscore, but if you are either using Lo-Dash or additional plugins like [underscore.string](https://github.com/epeli/underscore.string), we can end up clobbering existing functions.

Especially with Lo-Dash [beginning to expand its suite of string utils](https://github.com/lodash/lodash/issues/425), I'd like to see a safer way of mixing in contrib's functions. Underscore.string has a [basic implementation of this](https://github.com/epeli/underscore.string#nodejs-installation) where you can either mixin functions individually, or mixin everything.

The first thing that occurs to me is to add a `_.safeMixin` method that won't clobber stuff, and can potentially log which functions aren't being mixed in.

Of course, this might be something that should be fixed at the Underscore/Lo-Dash level instead.

Any thoughts on the best way to do this?

**Comment by jgonggrijp** [comment]
This will be solved by modularization.
