### ISSUE TITLE
Require either of underscore/lodash instead of always requiring underscore (npm)

### ISSUE THREAD

**Issue by joshuacc** [documentcloud/underscore-contrib#119]
Probably want to take care of safe mixins (#108) first to avoid conflicts with Lodash methods.

**Comment by jgonggrijp** [comment]
@joshuacc Since Lodash has only diverged from Underscore, I suggest closing this and putting our bets on the Fusion project instead.

**Comment by joshuacc** [comment]
@jgonggrijp Agreed
