### ISSUE TITLE
Add Bower and details of using dist files to docs

### ISSUE THREAD

**Issue by joshuacc** [documentcloud/underscore-contrib#159]
The Browser subsection should include a note about using Bower, as well as point out the existence of the `dist/*.js` files for those wishing to use all of contrib.

**Comment by jgonggrijp** [comment]
@joshuacc I think we can close this? Bower is end-of-life and the documentation about browser usage is going to change anyway when I modularize this.

**Comment by joshuacc** [comment]
@jgonggrijp 👍
