### ISSUE TITLE
_.setPath is not mutating the obj argument.

### ISSUE THREAD

**Issue by martincastell** [documentcloud/underscore-contrib#184]
According to the docs, _.setPath:
```
Sets the value of a property at any depth in obj based on the path described by the ks array. If any of the properties in the ks path don't exist, they will be created with defaultValue.

See _.updatePath about obj not being mutated in the process by cloning it.
```

Using _.updatePath would create a copy, it sounds like _.setPath should modify the original object, but it's not happening right now. JSFiddle: http://jsfiddle.net/ds2qa8bc/1/

**Comment by codelahoma** [comment]
@martincastell:

Both `_.setPath` and `_.updatePath` return new objects without mutating the one passed to them (they're both in the *object.builders* sub-library, after all).

Looking at the source, `_.setPath` actually calls `_.updatePath` to get its work done. 

The documentation you quoted is awkwardly worded. I believe the intent was to say that the lack of object mutation mentioned in the `_.updatePath` documentation applies to `_.setPath` as well, which it does.

I'll try to clarify the doc and submit a PR.
