### ISSUE TITLE
Feature request: AtLeast, AtMost

### ISSUE THREAD

**Issue by falafflepotatoe** [documentcloud/underscore-contrib#197]
heres an easy one, i always hate typing this one out:
- atLeast (cnt, value, array) returns bool
- atMost (cnt, value, array)  returns bool

example:

```
animals = [ 'cat','dog','bear','cat' ]
if (_atLeast(2, 'cat', animals))
  feedcats()
```

replaces

```
animals = ['cat','dog','bear','cat']
cnt = 0;
for (animal of animals){
  if (animal == 'cat'){
    cnt += 1
  }
}
if (cnt > 2){
     feedcats()
}
```

**Comment by reefdog** [comment]
So, basically:

```
_.containsAtLeast = function(list, count, value) {
  var filtered = _.filter(list, function(item) { return item == value; });
  return _.size(filtered) >= count;
}
```
and
```
_.containsAtMost = function(list, count, value) {
  var filtered = _.filter(list, function(item) { return item == value; });
  return _.size(filtered) <= count;
}
```

Notes:

1. Cool! Can you contribute?
2. Recommend `containsAtLeast/containsAtMost` because I don't think it's intuitive without the `contains` prefix
3. The `value` argument should probably support being a function, but if you want to punt on this for the first version, fine

**Comment by dioxmio** [comment]
done it in PR https://github.com/documentcloud/underscore-contrib/pull/208
