### ISSUE TITLE
_.pick don't work on documentation example

### ISSUE THREAD

**Issue by bakula** [documentcloud/underscore-contrib#198]
I've try to use _.pick just like in documentation but sadly dosn't work.
Jasmine test: http://jsfiddle.net/3VuGs/136/

**Comment by prabuinet** [comment]
use the latest version (1.8.3) : https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js

**Comment by reefdog** [comment]
`_.pick()` is a [core Underscore function](http://underscorejs.org/#pick), not an underscore-contrib one, but @prabuinet is correct. Using `_.pick()` the way you want requires 1.7.0 or newer.
