### ISSUE TITLE
_.partitionBy docs show _.keep instead

### ISSUE THREAD

**Issue by lucaslin** [documentcloud/underscore-contrib#211]
The docs for `partitionBy` show the signature as `_.keep(array:Array, fun:Function)`.

Maybe it just needs to be rebuilt?

The [current .md docs](https://github.com/documentcloud/underscore-contrib/blob/master/docs/underscore.array.selectors.js.md#partitionby) show the correct signature.

https://github.com/documentcloud/underscore-contrib/blob/master/index.html#L304

http://documentcloud.github.io/underscore-contrib/#partitionby

**Comment by jgonggrijp** [comment]
I was able to confirm that it just needs to be rebuilt. @joshuacc Do we build the docs only on release? In that case we can close this.

**Comment by joshuacc** [comment]
@jgonggrijp Yes, that is the current practice. Ideally I'd like to pull the built docs out of git entirely to avoid this sort of misunderstanding.
