### ISSUE TITLE
Status of this project? 2 commits in more than a year.

### ISSUE THREAD

**Issue by gaurav21r** [documentcloud/underscore-contrib#213]
**underscore-_contrib_** is such a wonderful project! We at https://github.com/rcorp really want to contribute here but wanted to ask the core maintainers the status of this project.

With 32 Open Issues and 16 Pull Requests and only **2 commits in 1 year and 2 months**, is there a maintenance issue with this project? Or are new contributions not accepted at the moment and the project is trying to achieve some **stability** ?

![image](https://cloud.githubusercontent.com/assets/1716462/13149189/801da6fe-d686-11e5-8419-6efbb0e29f9e.png)

**Comment by prakash1517** [comment]
Yaah,  please update the same  .....  :+1:

**Comment by codedogs** [comment]
@fogus Are you looking for new owners of this repo?

**Comment by jgonggrijp** [comment]
@gaurav21r We're back on track, if you're still interested in contributing. See #220.
